// <auto-generated />
using AASA_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AASA_Back_End.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230103214853_CreateCategoryTable")]
    partial class CreateCategoryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AASA_Back_End.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AASA_Back_End.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
