// <auto-generated />
using AASA_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AASA_Back_End.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230106094417_UpdateDatabse")]
    partial class UpdateDatabse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AASA_Back_End.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AASA_Back_End.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employeees");
                });

            modelBuilder.Entity("AASA_Back_End.Models.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageEighth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFifth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFourth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageNinth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSeventh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSixth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEighth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFifth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("TitleFourth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleNinth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSeventh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSixth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("AASA_Back_End.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("AASA_Back_End.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("DescriptionSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextThird")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFirst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleSecond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleThird")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
